/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package apps;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import xpertos.Home;

/**
 *
 * @author psaia
 */
public class Bmi extends javax.swing.JFrame {

    double bmi=0.00,weight=0.00,height=0.00;
    String name="";
    public Bmi() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p1 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SAVE = new javax.swing.JButton();
        history = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(558, 612));
        setMinimumSize(new java.awt.Dimension(558, 612));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("WEIGHT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 110, 70, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("ARE YOU FIT ?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 10, 260, 42);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(90, 60, 380, 60);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 110, 50, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("FITNESS METER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 410, 120, 20);
        getContentPane().add(p1);
        p1.setBounds(50, 360, 450, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("HEIGHT");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 110, 50, 17);

        jButton1.setText("CHECK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 210, 140, 50);
        getContentPane().add(t1);
        t1.setBounds(50, 140, 90, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xpertos/images/left-angle-bracket (1).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(390, 500, 32, 32);

        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });
        getContentPane().add(SAVE);
        SAVE.setBounds(50, 450, 90, 30);

        history.setText("HISTORY");
        history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyActionPerformed(evt);
            }
        });
        getContentPane().add(history);
        history.setBounds(410, 450, 100, 30);

        jLabel7.setText("FEET");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 150, 34, 14);
        getContentPane().add(t2);
        t2.setBounds(220, 140, 110, 40);

        jLabel8.setText("KG");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(480, 150, 34, 14);

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(410, 140, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
height = Double.parseDouble(t2.getText())/3.281;
weight = Double.parseDouble(t3.getText());
name = t1.getText();
bmi = weight / Math.pow(height, 2);

double weight1;
if(bmi >=18.5 && bmi <= 24.9)
{
    p1.setValue(100);
    JOptionPane.showMessageDialog(this,"congrats you are healthy");
}
if(bmi <18.5 )
{
    p1.setValue(25);
     weight1 = 21.5 * Math.pow(height,2 );
    JOptionPane.showMessageDialog(this,"you have to increase your weight by "+ Math.round((weight1-weight))+ " KG");
}
else if(bmi >24.9 && bmi <= 29.9)
{
    p1.setValue(75);
    weight1 = 21.5 * Math.pow(height,2 );
    JOptionPane.showMessageDialog(this,"You are over Healthy ! Need decrease your weight by "+ Math.round((weight-weight1))+ " KG");
}
else if(bmi > 29.9)
{
    p1.setValue(25);
    weight1 = 21.5 * Math.pow(height,2 );
    JOptionPane.showMessageDialog(this,"you really have to decresse your weight by "+ Math.round((weight-weight1))+ " KG");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MousePressed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        
if(name.equals("") | bmi==0.00 | height==0.00 | weight == 0.00 )
{JOptionPane.showMessageDialog(this,"please enter your details" );
      
}
else{
           String UpdateCmd = "insert into bmi set name ='"+name +"' , weight ='"+weight +"' ,height ='"+height +"', bmi ='"+bmi+"';";
         try{
            Class.forName("java.sql.Driver");
            Connection con1  = DriverManager.getConnection("jdbc:mysql://localhost:3306/xpertos", "root","");
            Statement s1 = con1.createStatement();
           
            s1.executeUpdate(UpdateCmd);
            JOptionPane.showMessageDialog(this,"your details havfe been saved" );
         }
        catch(Exception e)
        { JOptionPane.showMessageDialog(this, e);
        }}
    }//GEN-LAST:event_SAVEActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyActionPerformed
new BmiHistroy().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_historyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bmi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SAVE;
    private javax.swing.JButton history;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JProgressBar p1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables

}
