/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.event.KeyEvent;

/**
 *
 * @author home
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        a1.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        a1 = new javax.swing.JRadioButton();
        a2 = new javax.swing.JRadioButton();
        a3 = new javax.swing.JRadioButton();
        a4 = new javax.swing.JRadioButton();
        a5 = new javax.swing.JRadioButton();
        a6 = new javax.swing.JRadioButton();
        a7 = new javax.swing.JRadioButton();
        a8 = new javax.swing.JRadioButton();
        a9 = new javax.swing.JRadioButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        buttonGroup1.add(a1);
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(a2);
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        a2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                a2KeyPressed(evt);
            }
        });

        buttonGroup1.add(a3);
        a3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                a3KeyPressed(evt);
            }
        });

        buttonGroup1.add(a4);
        a4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                a4KeyPressed(evt);
            }
        });

        buttonGroup1.add(a5);
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });
        a5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                a5KeyPressed(evt);
            }
        });

        buttonGroup1.add(a6);
        a6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                a6KeyPressed(evt);
            }
        });

        buttonGroup1.add(a7);
        a7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                a7KeyPressed(evt);
            }
        });

        buttonGroup1.add(a8);
        a8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                a8KeyPressed(evt);
            }
        });

        buttonGroup1.add(a9);
        a9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                a9KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(a7)
                        .addGap(18, 18, 18)
                        .addComponent(a8)
                        .addGap(18, 18, 18)
                        .addComponent(a9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(a4)
                        .addGap(18, 18, 18)
                        .addComponent(a5)
                        .addGap(18, 18, 18)
                        .addComponent(a6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(a1)
                        .addGap(18, 18, 18)
                        .addComponent(a2)
                        .addGap(18, 18, 18)
                        .addComponent(a3)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1)
                    .addComponent(a2)
                    .addComponent(a3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a4)
                    .addComponent(a5)
                    .addComponent(a6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a7)
                    .addComponent(a8)
                    .addComponent(a9))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_DOWN)
{a3.setSelected(true);
a3.requestFocus();
}
else if(evt.getKeyCode()==KeyEvent.VK_RIGHT)
{  a2.setSelected(true);
a2.requestFocus();
}
    }//GEN-LAST:event_formKeyPressed

    private void a9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a9KeyPressed
if(evt.getKeyCode()==KeyEvent.VK_UP)
{  a6.setSelected(true);
a6.requestFocus();
}
else if(evt.getKeyCode()==KeyEvent.VK_LEFT)
{ a8.setSelected(true);     a8.requestFocus();}   // TODO add your handling code here:
    }//GEN-LAST:event_a9KeyPressed

    private void a7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a7KeyPressed
if(evt.getKeyCode()==KeyEvent.VK_UP)
{a4.setSelected(true);
a4.requestFocus();
}
else if(evt.getKeyCode()==KeyEvent.VK_RIGHT)
{  a8.setSelected(true)
        ;a8.requestFocus();
}        // TODO add your handling code here:
    }//GEN-LAST:event_a7KeyPressed

    private void a3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a3KeyPressed
if(evt.getKeyCode()==KeyEvent.VK_DOWN)
{ a6.setSelected(true);
a6.requestFocus();}
else if(evt.getKeyCode()==KeyEvent.VK_LEFT)
 {
     a2.setSelected(true);
     a2.requestFocus();
 }        // TODO add your handling code here:
    }//GEN-LAST:event_a3KeyPressed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    private void a2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a2KeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_DOWN:
                a5.setSelected(true);
                a5.requestFocus();
                break;
            case KeyEvent.VK_RIGHT:
                a3.setSelected(true);
                a3.requestFocus();
                break;
            case KeyEvent.VK_LEFT:
                
                a1.setSelected(true);
// TODO add your handling code here:
                a1.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_a2KeyPressed

    private void a8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a8KeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP:
                a5.setSelected(true);
                a5.requestFocus();
                break;
            case KeyEvent.VK_RIGHT:
                
                a9.setSelected(true);
                a9.requestFocus();
                break;
            case KeyEvent.VK_LEFT:
                a8.setSelected(true);        // TODO add your handling code here:
                a8.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_a8KeyPressed

    private void a4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a4KeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_DOWN:
                a7.setSelected(true);
                a7.requestFocus();
                break;
            case KeyEvent.VK_RIGHT:
                a5.setSelected(true);
                a5.requestFocus();
                break;
            case KeyEvent.VK_UP:
                a1.setSelected(true);
                a1.requestFocus();// TODO add your handling code here:
                break;
            default:
                break;
        }
    }//GEN-LAST:event_a4KeyPressed

    private void a6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a6KeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_DOWN:
                a9.setSelected(true);
                a9.requestFocus();
                break;
            case KeyEvent.VK_LEFT:
                a5.setSelected(true);
                a5.requestFocus();
                break;
            case KeyEvent.VK_UP:
                a3.setSelected(true);         // TODO add your handling code here:
                a3.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_a6KeyPressed

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a5ActionPerformed

    private void a5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a5KeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_DOWN:
                a8.setSelected(true);
                a8.requestFocus();
                break;
            case KeyEvent.VK_RIGHT:
                a6.setSelected(true);
                a6.requestFocus();
                break;
            case KeyEvent.VK_UP:
                a2.setSelected(true);
                a2.requestFocus();
                break;
        // TODO add your handling code here:
            case KeyEvent.VK_LEFT:
                a4.setSelected(true);
                a4.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_a5KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton a2;
    private javax.swing.JRadioButton a3;
    private javax.swing.JRadioButton a4;
    private javax.swing.JRadioButton a5;
    private javax.swing.JRadioButton a6;
    private javax.swing.JRadioButton a7;
    private javax.swing.JRadioButton a8;
    private javax.swing.JRadioButton a9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
