/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aakash12B;

/**
 *
 * @author home
 */
public class EqSolver extends javax.swing.JFrame {
double flag = 0,a1=0,a2=0,a3=0;
String a ="" , b="", c="";
    /**
     * Creates new form EqSolver
     */
    public EqSolver() {
        initComponents();
  
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        nine1 = new javax.swing.JButton();
        nine2 = new javax.swing.JButton();
        nine3 = new javax.swing.JButton();
        nine4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        result = new java.awt.TextField();
        calc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(460, 483));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seven.setBackground(new java.awt.Color(255, 255, 255));
        seven.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        seven.setText("7");
        seven.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        seven.setFocusable(false);
        seven.setMargin(new java.awt.Insets(0, 0, 0, 0));
        seven.setMaximumSize(new java.awt.Dimension(80, 80));
        seven.setMinimumSize(new java.awt.Dimension(80, 80));
        seven.setPreferredSize(new java.awt.Dimension(40, 40));
        seven.setRequestFocusEnabled(false);
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        getContentPane().add(seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 60, 60));

        eight.setBackground(new java.awt.Color(255, 255, 255));
        eight.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        eight.setText("8");
        eight.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        eight.setFocusable(false);
        eight.setMargin(new java.awt.Insets(0, 0, 0, 0));
        eight.setMaximumSize(new java.awt.Dimension(80, 80));
        eight.setMinimumSize(new java.awt.Dimension(80, 80));
        eight.setPreferredSize(new java.awt.Dimension(40, 40));
        eight.setRequestFocusEnabled(false);
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        getContentPane().add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 60, 60));

        nine.setBackground(new java.awt.Color(255, 255, 255));
        nine.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        nine.setText("-");
        nine.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        nine.setFocusable(false);
        nine.setMargin(new java.awt.Insets(0, 0, 0, 0));
        nine.setMaximumSize(new java.awt.Dimension(80, 80));
        nine.setMinimumSize(new java.awt.Dimension(80, 80));
        nine.setPreferredSize(new java.awt.Dimension(40, 40));
        nine.setRequestFocusEnabled(false);
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        getContentPane().add(nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 60, 60));

        four.setBackground(new java.awt.Color(255, 255, 255));
        four.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        four.setText("4");
        four.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        four.setFocusable(false);
        four.setMargin(new java.awt.Insets(0, 0, 0, 0));
        four.setMaximumSize(new java.awt.Dimension(80, 80));
        four.setMinimumSize(new java.awt.Dimension(80, 80));
        four.setPreferredSize(new java.awt.Dimension(40, 40));
        four.setRequestFocusEnabled(false);
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        getContentPane().add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 60, 60));

        five.setBackground(new java.awt.Color(255, 255, 255));
        five.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        five.setText("5");
        five.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        five.setFocusable(false);
        five.setMargin(new java.awt.Insets(0, 0, 0, 0));
        five.setMaximumSize(new java.awt.Dimension(80, 80));
        five.setMinimumSize(new java.awt.Dimension(80, 80));
        five.setPreferredSize(new java.awt.Dimension(40, 40));
        five.setRequestFocusEnabled(false);
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        getContentPane().add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 60, 60));

        six.setBackground(new java.awt.Color(255, 255, 255));
        six.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        six.setText("6");
        six.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        six.setFocusable(false);
        six.setMargin(new java.awt.Insets(0, 0, 0, 0));
        six.setMaximumSize(new java.awt.Dimension(80, 80));
        six.setMinimumSize(new java.awt.Dimension(80, 80));
        six.setPreferredSize(new java.awt.Dimension(40, 40));
        six.setRequestFocusEnabled(false);
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        getContentPane().add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 60, 60));

        one.setBackground(new java.awt.Color(255, 255, 255));
        one.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        one.setText("1");
        one.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        one.setFocusable(false);
        one.setMargin(new java.awt.Insets(0, 0, 0, 0));
        one.setMaximumSize(new java.awt.Dimension(80, 80));
        one.setMinimumSize(new java.awt.Dimension(80, 80));
        one.setPreferredSize(new java.awt.Dimension(40, 40));
        one.setRequestFocusEnabled(false);
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        getContentPane().add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 60, 60));

        two.setBackground(new java.awt.Color(255, 255, 255));
        two.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        two.setText("2");
        two.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        two.setFocusable(false);
        two.setMargin(new java.awt.Insets(0, 0, 0, 0));
        two.setMaximumSize(new java.awt.Dimension(80, 80));
        two.setMinimumSize(new java.awt.Dimension(80, 80));
        two.setPreferredSize(new java.awt.Dimension(40, 40));
        two.setRequestFocusEnabled(false);
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        getContentPane().add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 60, 60));

        three.setBackground(new java.awt.Color(255, 255, 255));
        three.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        three.setText("3");
        three.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        three.setFocusable(false);
        three.setMargin(new java.awt.Insets(0, 0, 0, 0));
        three.setMaximumSize(new java.awt.Dimension(80, 80));
        three.setMinimumSize(new java.awt.Dimension(80, 80));
        three.setPreferredSize(new java.awt.Dimension(40, 40));
        three.setRequestFocusEnabled(false);
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        getContentPane().add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 60, 60));

        zero.setBackground(new java.awt.Color(255, 255, 255));
        zero.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        zero.setText("0");
        zero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        getContentPane().add(zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 200, 60));

        nine1.setBackground(new java.awt.Color(255, 255, 255));
        nine1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        nine1.setText("9");
        nine1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        nine1.setFocusable(false);
        nine1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        nine1.setMaximumSize(new java.awt.Dimension(80, 80));
        nine1.setMinimumSize(new java.awt.Dimension(80, 80));
        nine1.setPreferredSize(new java.awt.Dimension(40, 40));
        nine1.setRequestFocusEnabled(false);
        nine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nine1ActionPerformed(evt);
            }
        });
        getContentPane().add(nine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 60, 60));

        nine2.setBackground(new java.awt.Color(255, 255, 255));
        nine2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        nine2.setText(" x2");
        nine2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        nine2.setFocusable(false);
        nine2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        nine2.setMaximumSize(new java.awt.Dimension(80, 80));
        nine2.setMinimumSize(new java.awt.Dimension(80, 80));
        nine2.setPreferredSize(new java.awt.Dimension(40, 40));
        nine2.setRequestFocusEnabled(false);
        nine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nine2ActionPerformed(evt);
            }
        });
        getContentPane().add(nine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 60, 60));

        nine3.setBackground(new java.awt.Color(255, 255, 255));
        nine3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        nine3.setText(" x");
        nine3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        nine3.setFocusable(false);
        nine3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        nine3.setMaximumSize(new java.awt.Dimension(80, 80));
        nine3.setMinimumSize(new java.awt.Dimension(80, 80));
        nine3.setPreferredSize(new java.awt.Dimension(40, 40));
        nine3.setRequestFocusEnabled(false);
        nine3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nine3ActionPerformed(evt);
            }
        });
        getContentPane().add(nine3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 60, 60));

        nine4.setBackground(new java.awt.Color(255, 255, 255));
        nine4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        nine4.setText("+");
        nine4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        nine4.setFocusable(false);
        nine4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        nine4.setMaximumSize(new java.awt.Dimension(80, 80));
        nine4.setMinimumSize(new java.awt.Dimension(80, 80));
        nine4.setPreferredSize(new java.awt.Dimension(40, 40));
        nine4.setRequestFocusEnabled(false);
        nine4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nine4ActionPerformed(evt);
            }
        });
        getContentPane().add(nine4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 60, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("= 0 ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        result.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });
        result.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                resultTextValueChanged(evt);
            }
        });
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 210, 30));

        calc.setBackground(new java.awt.Color(255, 255, 255));
        calc.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        calc.setText("calc ");
        calc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcActionPerformed(evt);
            }
        });
        getContentPane().add(calc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 200, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        result.setText(result.getText() + "7");
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        
        result.setText( result.getText() + "8");
        
        // TODO t your handling code here:
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
      
        result.setText(result.getText() + " -");
        
       
    }//GEN-LAST:event_nineActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        result.setText(result.getText() + "4");
        
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        result.setText(result.getText() + "5");
        
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        result.setText(result.getText() + "6");
        
    }//GEN-LAST:event_sixActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed

        result.setText(result.getText() + "1");
        
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        result.setText(result.getText() + "2");
        
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        result.setText(result.getText() + "3");
    }//GEN-LAST:event_threeActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        result.setText(result.getText() + "0");
     
    }//GEN-LAST:event_zeroActionPerformed

    private void nine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nine1ActionPerformed
result.setText(result.getText() + "9");        
    }//GEN-LAST:event_nine1ActionPerformed

    private void nine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nine2ActionPerformed
if (flag==0)
{flag =1;}
result.setText(result.getText() + "x^2"); 
    }//GEN-LAST:event_nine2ActionPerformed

    private void nine3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nine3ActionPerformed
result.setText(result.getText() + "x"); 
    }//GEN-LAST:event_nine3ActionPerformed

    private void nine4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nine4ActionPerformed
result.setText(result.getText()  +" +"); 
    }//GEN-LAST:event_nine4ActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultActionPerformed

    private void resultTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_resultTextValueChanged
        
        if(!result.getText().endsWith("x^2")&&flag==0)
        {
           
           a=result.getText();
           jLabel2.setText(a);
           
        }
        /////////////
        if(a=="")
               a="1";
        ///////////////
        else if (result.getText().endsWith("x^2"))
        {
            flag=1;
        }
         else if (!result.getText().endsWith("x") && flag ==1)
        {
            b=result.getText().substring(a.length()+3,result.getText().length());
           jLabel2.setText(b);
        }
        //////////
      if(b=="")
               b="1";
      //////////////// 
      else if (result.getText().endsWith("x"))
        {
            flag=2;
        }
         else if (flag ==2&& !result.getText().endsWith("x"))
        {
            c=result.getText().substring((a.length()+3) +(b.length()+1),result.getText().length());
           jLabel2.setText(c);
        }
      
    }//GEN-LAST:event_resultTextValueChanged

    private void calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcActionPerformed

   a1=Double.parseDouble(a);
       a2=Double.parseDouble(b);
       a3=Double.parseDouble(c);
    jLabel2.setText("" +(a1+a2+a3)); 
    }//GEN-LAST:event_calcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EqSolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EqSolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EqSolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EqSolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /////////////////////////////////////

        
        
        
        /////////////////////////////////////////
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EqSolver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calc;
    private javax.swing.JButton eight;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nine;
    private javax.swing.JButton nine1;
    private javax.swing.JButton nine2;
    private javax.swing.JButton nine3;
    private javax.swing.JButton nine4;
    private javax.swing.JButton one;
    private java.awt.TextField result;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
