/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xpertos;

import apps.feedback;
import apps.Contacts;
import apps.Bmi;
import AppPackage.AnimationClass;
import aakashcalc11b.Calculator;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author psaia
 */
public class Home extends javax.swing.JFrame {
boolean b = false;
    /**
     * Creates new form backupHS
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xpertos", "root","");
            Statement s = con.createStatement();
            ResultSet r;
           }
        catch(Exception e)
        { JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contacts = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        calc = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        youtube = new javax.swing.JLabel();
        settings = new javax.swing.JLabel();
        feedback = new javax.swing.JLabel();
        help = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bmi = new javax.swing.JLabel();
        card = new javax.swing.JLabel();
        cc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 730));
        setMinimumSize(new java.awt.Dimension(1280, 730));
        setPreferredSize(new java.awt.Dimension(1280, 730));
        setResizable(false);
        getContentPane().setLayout(null);

        contacts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xpertos/images/contacts.png"))); // NOI18N
        contacts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contactsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                contactsMouseReleased(evt);
            }
        });
        getContentPane().add(contacts);
        contacts.setBounds(460, 590, 100, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xpertos/images/AppDrawer.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(600, 590, 100, 100);

        calc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xpertos/images/calculator.png"))); // NOI18N
        calc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                calcMousePressed(evt);
            }
        });
        getContentPane().add(calc);
        calc.setBounds(870, 590, 100, 100);

        phone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xpertos/images/phone.png"))); // NOI18N
        getContentPane().add(phone);
        phone.setBounds(320, 590, 100, 100);

        youtube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xpertos/images/youtube.png"))); // NOI18N
        youtube.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                youtubeMousePressed(evt);
            }
        });
        getContentPane().add(youtube);
        youtube.setBounds(730, 590, 100, 100);

        settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xpertos/images/Webp.net-resizeimage (1).png"))); // NOI18N
        getContentPane().add(settings);
        settings.setBounds(190, -120, 100, 120);

        feedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xpertos/images/Webp.net-resizeimage.png"))); // NOI18N
        feedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                feedbackMousePressed(evt);
            }
        });
        getContentPane().add(feedback);
        feedback.setBounds(1300, 210, 110, 110);

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xpertos/images/help.png"))); // NOI18N
        getContentPane().add(help);
        help.setBounds(200, 590, 100, 110);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 590, 100, 110);

        bmi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xpertos/images/fitness-color-16-512.png"))); // NOI18N
        bmi.setText("jLabel2");
        bmi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bmiMouseReleased(evt);
            }
        });
        getContentPane().add(bmi);
        bmi.setBounds(1010, 590, 100, 120);

        card.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        card.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        card.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xpertos/images/rounded-rectangle-512 (1) (1).png"))); // NOI18N
        card.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cardMouseReleased(evt);
            }
        });
        getContentPane().add(card);
        card.setBounds(20, 660, 1230, 690);

        cc.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cc.setForeground(new java.awt.Color(255, 0, 0));
        cc.setText(" © SAI AAKASH APS BANGALORE");
        getContentPane().add(cc);
        cc.setBounds(310, 160, 640, 130);

        jLabel3.setForeground(new java.awt.Color(30, 58, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xpertos/images/wp1.jpeg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactsMouseClicked

    }//GEN-LAST:event_contactsMouseClicked

    private void contactsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactsMousePressed

    }//GEN-LAST:event_contactsMousePressed

    private void contactsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactsMouseReleased
        new Contacts().setVisible(true);
        dispose();
    }//GEN-LAST:event_contactsMouseReleased

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
        if(b==false )
        {    AnimationClass ab = new AnimationClass();
            ab.jLabelYUp(660, 20,1, 4, card);
            ab.jLabelYUp(590, 70,1, 4, contacts);
            ab.jLabelYUp(590, 70,1, 4, youtube);
            ab.jLabelYUp(590, 70,1, 4, phone);
            ab.jLabelYUp(590, 70,1, 4, calc);
            ab.jLabelXLeft(1300, 870, 1, 2, feedback);
            ab.jLabelYDown(-120,60 ,1, 4, settings);
            ab.jLabelYUp(590, 210,1, 4, help);
            ab.jLabelYUp(590, 70,1, 4, bmi);
            b=true;
        }
        else
        {
            AnimationClass ab = new AnimationClass();
            ab.jLabelYDown(20, 660,1, 4, card);
            ab.jLabelYDown(70, 590,1, 4, contacts);
            ab.jLabelYDown(70, 590,1, 4, youtube);
            ab.jLabelYDown(70, 590,1, 4, phone);
            ab.jLabelYDown(70, 590,1, 4, calc);
            ab.jLabelXRight(870, 1300, 1, 2, feedback);
            ab.jLabelYUp(60,-120 ,1, 2, settings);
            ab.jLabelYDown(210, 590,1, 4, help);
            ab.jLabelYDown(70, 590,1, 4, bmi);
            b= false;
        }
    }//GEN-LAST:event_jLabel4MouseReleased

    private void calcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcMouseClicked

    }//GEN-LAST:event_calcMouseClicked

    private void calcMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcMousePressed
        new Calculator().setVisible(true);
        dispose();
    }//GEN-LAST:event_calcMousePressed

    private void youtubeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_youtubeMousePressed
        try {

            java.awt.Desktop.getDesktop().browse(java.net.URI.create("https://www.youtube.com"));
        }
        catch (java.io.IOException e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_youtubeMousePressed

    private void feedbackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackMousePressed
        new feedback().setVisible(true);
        dispose();
    }//GEN-LAST:event_feedbackMousePressed

    private void cardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardMouseReleased

    }//GEN-LAST:event_cardMouseReleased

    private void bmiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmiMouseReleased
        new Bmi().setVisible(true);
        dispose();
    }//GEN-LAST:event_bmiMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bmi;
    private javax.swing.JLabel calc;
    private javax.swing.JLabel card;
    private javax.swing.JLabel cc;
    private javax.swing.JLabel contacts;
    private javax.swing.JLabel feedback;
    private javax.swing.JLabel help;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel settings;
    private javax.swing.JLabel youtube;
    // End of variables declaration//GEN-END:variables
}
